"""Initial migration

Revision ID: de2d9a107796
Revises: 
Create Date: 2024-08-28 11:40:28.385864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'de2d9a107796'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_zone')
    op.drop_table('business_hours')
    op.drop_table('store')
    op.drop_table('store_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_status',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('timestamp_utc', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('store',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('timestamp_utc', mysql.DATETIME(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('business_hours',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('day_of_week', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_time_local', mysql.TIME(), nullable=False),
    sa.Column('end_time_local', mysql.TIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('time_zone',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('store_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('timezone_str', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
